/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingmachine;
/*
 * @author http://www.twitch.tv/diomondplaysgames
 */
public class VendingMachineUI extends javax.swing.JFrame {
    double money = 0;
    
    double GB_cost = 1.15;
    double CLIF_cost = 2.00;
    double cheetos_cost = 2.50;
    double KK_cost = 1.50;
    double cookie_cost = 1.00;
    double doritos_cost = 2.50;
    double lays_cost = 2.50;
    double nuts_cost = 0.75;
    double pretzel_cost = 0.60;
    double ruffles_cost = 2.50;
    double skittles_cost = 1.20;
    double twix_cost = 2.00;
    
    public VendingMachineUI() {
        initComponents();
    }
    
    public void changecalc(){
        
        while (money += 0.05){
            
        }
        
    }
    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cheetos = new javax.swing.JRadioButton();
        cookie = new javax.swing.JRadioButton();
        GB = new javax.swing.JRadioButton();
        CLIF = new javax.swing.JRadioButton();
        doritos = new javax.swing.JRadioButton();
        nuts = new javax.swing.JRadioButton();
        pretzel = new javax.swing.JRadioButton();
        ruffles = new javax.swing.JRadioButton();
        lays = new javax.swing.JRadioButton();
        skittles = new javax.swing.JRadioButton();
        twix = new javax.swing.JRadioButton();
        KK = new javax.swing.JRadioButton();
        cancel = new javax.swing.JButton();
        buy = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        moneyOP = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        changeOP = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nickel = new javax.swing.JButton();
        dime = new javax.swing.JButton();
        quarter = new javax.swing.JButton();
        loonie = new javax.swing.JButton();
        toonie = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        jRadioButton2.setText("jRadioButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Vending Machine");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Please Choose A Food");
        jLabel2.setPreferredSize(new java.awt.Dimension(260, 30));

        cheetos.setText("Cheetos Puffs");
        cheetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheetosActionPerformed(evt);
            }
        });

        cookie.setText("Chocolate Chip Cookie");
        cookie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cookieActionPerformed(evt);
            }
        });

        GB.setText("Quaker Granola Bar");
        GB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GBActionPerformed(evt);
            }
        });

        CLIF.setText("CLIF Bar");
        CLIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLIFActionPerformed(evt);
            }
        });

        doritos.setText("Doritos");
        doritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doritosActionPerformed(evt);
            }
        });

        nuts.setText("Roasted Peanuts");
        nuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutsActionPerformed(evt);
            }
        });

        pretzel.setText("Mini Pretzels");
        pretzel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pretzelActionPerformed(evt);
            }
        });

        ruffles.setText("Ruffles All Dressed");
        ruffles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rufflesActionPerformed(evt);
            }
        });

        lays.setText("Lays Original Potato Chips");
        lays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laysActionPerformed(evt);
            }
        });

        skittles.setText("Skittles");
        skittles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skittlesActionPerformed(evt);
            }
        });

        twix.setText("Twix");
        twix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twixActionPerformed(evt);
            }
        });

        KK.setText("Kit Kat");
        KK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KKActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        buy.setText("Purchase");
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });

        clear.setText("Clear Selection");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel3.setText("$2.50");

        jLabel4.setText("$1.00");

        jLabel5.setText("$1.15");

        jLabel6.setText("$2.00");

        jLabel7.setText("$2.50");

        jLabel8.setText("$0.75");

        jLabel9.setText("$0.60");

        jLabel10.setText("$2.50");

        jLabel11.setText("$2.50");

        jLabel12.setText("$1.25");

        jLabel13.setText("$2.00");

        jLabel14.setText("$1.50");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Inserted Money:");

        moneyOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyOPActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Change:");

        changeOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeOPActionPerformed(evt);
            }
        });

        jLabel17.setText("$");

        jLabel18.setText("$");

        nickel.setText("Nickel");
        nickel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nickelActionPerformed(evt);
            }
        });

        dime.setText("Dime");
        dime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimeActionPerformed(evt);
            }
        });

        quarter.setText("Quarter");
        quarter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quarterActionPerformed(evt);
            }
        });

        loonie.setText("Loonie");
        loonie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loonieActionPerformed(evt);
            }
        });

        toonie.setText("Toonie");
        toonie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toonieActionPerformed(evt);
            }
        });

        jLabel19.setText("$0.05");

        jLabel20.setText("$0.10");

        jLabel21.setText("$0.25");

        jLabel22.setText("$1.00");

        jLabel23.setText("$2.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cheetos)
                    .addComponent(pretzel)
                    .addComponent(skittles)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(CLIF)
                        .addComponent(jLabel6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cookie)
                            .addComponent(doritos)
                            .addComponent(twix)
                            .addComponent(ruffles))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lays)
                            .addComponent(KK)
                            .addComponent(GB)
                            .addComponent(nuts))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(123, 123, 123))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(122, 122, 122))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(cancel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nickel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addGap(29, 29, 29)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dime)
                                        .addGap(10, 10, 10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quarter)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel21)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(loonie)
                                        .addGap(10, 10, 10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel22)
                                        .addGap(27, 27, 27)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(toonie)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel23))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(clear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buy)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(218, 218, 218)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(changeOP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moneyOP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moneyOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cheetos)
                    .addComponent(cookie)
                    .addComponent(GB))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CLIF)
                    .addComponent(doritos)
                    .addComponent(nuts))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pretzel)
                    .addComponent(ruffles)
                    .addComponent(lays))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KK)
                    .addComponent(twix)
                    .addComponent(skittles))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toonie)
                    .addComponent(loonie)
                    .addComponent(quarter)
                    .addComponent(dime)
                    .addComponent(nickel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(buy)
                    .addComponent(clear))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GBActionPerformed
        //Select Only One
        
        if (GB.isSelected()) {
            CLIF.setSelected(false);
            KK.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_GBActionPerformed

    private void CLIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLIFActionPerformed
        //Set Only One
        if (CLIF.isSelected()){
            GB.setSelected(false);
            KK.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_CLIFActionPerformed

    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed
        //Purchase and give change
        money = Double.parseDouble(moneyOP.getText());
        
        if (GB.isSelected()){
            money = money - GB_cost;
            changeOP.setText(Double.toString(money));
        }else if(CLIF.isSelected()){
            money = money - CLIF_cost;
            changeOP.setText(Double.toString(money));
        }else if(cheetos.isSelected()){
            money = money - cheetos_cost;
            changeOP.setText(Double.toString(money));
        }else if(KK.isSelected()){
            money = money - KK_cost;
            changeOP.setText(Double.toString(money));
        }else if(cookie.isSelected()){
            money = money - cookie_cost;
            changeOP.setText(Double.toString(money));
        }else if(doritos.isSelected()){
            money = money - doritos_cost;
            changeOP.setText(Double.toString(money));
        }else if(lays.isSelected()){
            money = money - lays_cost;
            changeOP.setText(Double.toString(money));
        }else if(nuts.isSelected()){
            money = money - nuts_cost;
            changeOP.setText(Double.toString(money));
        }else if(pretzel.isSelected()){
            money = money - pretzel_cost;
            changeOP.setText(Double.toString(money));
        }else if(ruffles.isSelected()){
            money = money - ruffles_cost;
            changeOP.setText(Double.toString(money));
        }else if(skittles.isSelected()){
            money = money - skittles_cost;
            changeOP.setText(Double.toString(money));
        }else if(twix.isSelected()){
            money = money - twix_cost;
            changeOP.setText(Double.toString(money));
        }
        
        if (money < 0 || money > 10){
            changeOP.setText("ERROR");
        }else{
            changeOP.setText(Double.toString(money));
        }
    }//GEN-LAST:event_buyActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        //Exit The GUI
        System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        //Clear all selections and textfields
        CLIF.setSelected(false);
        GB.setSelected(false);
        KK.setSelected(false);
        cheetos.setSelected(false);
        cookie.setSelected(false);
        doritos.setSelected(false);
        lays.setSelected(false);
        nuts.setSelected(false);
        pretzel.setSelected(false);
        ruffles.setSelected(false);
        skittles.setSelected(false);
        twix.setSelected(false);
        
        moneyOP.setText(" ");
        changeOP.setText(" ");
    }//GEN-LAST:event_clearActionPerformed

    private void cheetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheetosActionPerformed
        //Set Only One
        if (cheetos.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            KK.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_cheetosActionPerformed

    private void cookieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cookieActionPerformed
        //Set Only One
        if (cookie.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            cheetos.setSelected(false);
            KK.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_cookieActionPerformed

    private void doritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doritosActionPerformed
        //Set Only One
        if (doritos.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            KK.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_doritosActionPerformed

    private void KKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KKActionPerformed
        //Set Only One
        if (KK.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_KKActionPerformed

    private void laysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laysActionPerformed
        //Set Only One
        if (lays.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            KK.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_laysActionPerformed

    private void nutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutsActionPerformed
        //Set Only One
        if (nuts.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            KK.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_nutsActionPerformed

    private void pretzelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pretzelActionPerformed
        //Set Only One
        if (pretzel.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            KK.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_pretzelActionPerformed

    private void rufflesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rufflesActionPerformed
        //Set Only One
        if (ruffles.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            KK.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_rufflesActionPerformed

    private void skittlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skittlesActionPerformed
        //Set Only One
        if (skittles.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            KK.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_skittlesActionPerformed

    private void twixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twixActionPerformed
        //Set Only One
        if (twix.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            KK.setSelected(false);
        }
    }//GEN-LAST:event_twixActionPerformed

    private void moneyOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyOPActionPerformed
        //don't change
    }//GEN-LAST:event_moneyOPActionPerformed

    private void changeOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeOPActionPerformed
        //don't change
    }//GEN-LAST:event_changeOPActionPerformed

    private void quarterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quarterActionPerformed
        //add $0.25
        money += 0.25;
        
    }//GEN-LAST:event_quarterActionPerformed

    private void nickelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nickelActionPerformed
        //add $0.05
        money += 0.05;
        
    }//GEN-LAST:event_nickelActionPerformed

    private void dimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimeActionPerformed
        //add $0.10
        money += 0.10;
        
    }//GEN-LAST:event_dimeActionPerformed

    private void loonieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loonieActionPerformed
        //add $1.00
        money += 1.00;
        
    }//GEN-LAST:event_loonieActionPerformed

    private void toonieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toonieActionPerformed
        //add $2.00
        money += 2.00;
        
    }//GEN-LAST:event_toonieActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendingMachineUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VendingMachineUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CLIF;
    private javax.swing.JRadioButton GB;
    private javax.swing.JRadioButton KK;
    private javax.swing.JButton buy;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField changeOP;
    private javax.swing.JRadioButton cheetos;
    private javax.swing.JButton clear;
    private javax.swing.JRadioButton cookie;
    private javax.swing.JButton dime;
    private javax.swing.JRadioButton doritos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton lays;
    private javax.swing.JButton loonie;
    private javax.swing.JTextField moneyOP;
    private javax.swing.JButton nickel;
    private javax.swing.JRadioButton nuts;
    private javax.swing.JRadioButton pretzel;
    private javax.swing.JButton quarter;
    private javax.swing.JRadioButton ruffles;
    private javax.swing.JRadioButton skittles;
    private javax.swing.JButton toonie;
    private javax.swing.JRadioButton twix;
    // End of variables declaration//GEN-END:variables
}