/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingmachine;
/*
 * @author http://www.twitch.tv/diomondplaysgames
 */
import java.util.Scanner;
import java.lang.Math;
import javax.swing.JOptionPane;
public class VendingMachineUI extends javax.swing.JFrame {
    /**
     * Creates new form VendingMachineUI
     */
    public VendingMachineUI() {
        initComponents();
    }
    public void changecalc() {
        Scanner scan = new Scanner(System.in);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cheetos = new javax.swing.JRadioButton();
        cookie = new javax.swing.JRadioButton();
        GB = new javax.swing.JRadioButton();
        CLIF = new javax.swing.JRadioButton();
        doritos = new javax.swing.JRadioButton();
        nuts = new javax.swing.JRadioButton();
        pretzel = new javax.swing.JRadioButton();
        ruffles = new javax.swing.JRadioButton();
        lays = new javax.swing.JRadioButton();
        skittles = new javax.swing.JRadioButton();
        twix = new javax.swing.JRadioButton();
        KK = new javax.swing.JRadioButton();
        cancel = new javax.swing.JButton();
        buy = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        moneyOP = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        changeOP = new javax.swing.JTextField();

        jRadioButton2.setText("jRadioButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Vending Machine");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Please Choose A Food");
        jLabel2.setPreferredSize(new java.awt.Dimension(260, 30));

        cheetos.setText("Cheetos Puffs");
        cheetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheetosActionPerformed(evt);
            }
        });

        cookie.setText("Chocolate Chip Cookie");
        cookie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cookieActionPerformed(evt);
            }
        });

        GB.setText("Quaker Granola Bar");
        GB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GBActionPerformed(evt);
            }
        });

        CLIF.setText("CLIF Bar");
        CLIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLIFActionPerformed(evt);
            }
        });

        doritos.setText("Doritos");
        doritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doritosActionPerformed(evt);
            }
        });

        nuts.setText("Roasted Peanuts");
        nuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutsActionPerformed(evt);
            }
        });

        pretzel.setText("Mini Pretzels");
        pretzel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pretzelActionPerformed(evt);
            }
        });

        ruffles.setText("Ruffles All Dressed");
        ruffles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rufflesActionPerformed(evt);
            }
        });

        lays.setText("Lays Original Potato Chips");
        lays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laysActionPerformed(evt);
            }
        });

        skittles.setText("Skittles");
        skittles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skittlesActionPerformed(evt);
            }
        });

        twix.setText("Twix");
        twix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twixActionPerformed(evt);
            }
        });

        KK.setText("Kit Kat");
        KK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KKActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        buy.setText("Purchase");
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });

        clear.setText("Clear Selection");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel3.setText("$2.50");

        jLabel4.setText("$1.00");

        jLabel5.setText("$1.15");

        jLabel6.setText("$2.00");

        jLabel7.setText("$2.50");

        jLabel8.setText("$0.75");

        jLabel9.setText("$0.60");

        jLabel10.setText("$2.50");

        jLabel11.setText("$2.50");

        jLabel12.setText("$1.25");

        jLabel13.setText("$2.00");

        jLabel14.setText("$1,50");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Insert Money:");

        moneyOP.setText("$");
        moneyOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyOPActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Change:");

        changeOP.setText("$");
        changeOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeOPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cheetos)
                    .addComponent(pretzel)
                    .addComponent(skittles)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(CLIF)
                        .addComponent(jLabel6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cookie)
                            .addComponent(doritos)
                            .addComponent(twix)
                            .addComponent(ruffles))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lays)
                            .addComponent(KK)
                            .addComponent(GB)
                            .addComponent(nuts))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(123, 123, 123))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(122, 122, 122))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancel)
                                .addGap(30, 30, 30)
                                .addComponent(clear)
                                .addGap(30, 30, 30)
                                .addComponent(buy))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(moneyOP, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(changeOP))))
                        .addGap(240, 240, 240))))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(218, 218, 218)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(moneyOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(changeOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cheetos)
                    .addComponent(cookie)
                    .addComponent(GB))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CLIF)
                    .addComponent(doritos)
                    .addComponent(nuts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pretzel)
                    .addComponent(ruffles)
                    .addComponent(lays))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skittles)
                    .addComponent(twix)
                    .addComponent(KK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(buy)
                    .addComponent(clear))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GBActionPerformed
        //Select Only One
        
        if (GB.isSelected()) {
            CLIF.setSelected(false);
            KK.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_GBActionPerformed

    private void CLIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLIFActionPerformed
        //Set Only One
        if (CLIF.isSelected()){
            GB.setSelected(false);
            KK.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_CLIFActionPerformed

    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed
        //Purchase and give change
        
    }//GEN-LAST:event_buyActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        //Exit The GUI
        System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        //Clear all selections and textfields
        CLIF.setSelected(false);
        GB.setSelected(false);
        KK.setSelected(false);
        cheetos.setSelected(false);
        cookie.setSelected(false);
        doritos.setSelected(false);
        lays.setSelected(false);
        nuts.setSelected(false);
        pretzel.setSelected(false);
        ruffles.setSelected(false);
        skittles.setSelected(false);
        twix.setSelected(false);
        
        moneyOP.setText("$ ");
        changeOP.setText("$ ");
    }//GEN-LAST:event_clearActionPerformed

    private void cheetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheetosActionPerformed
        //Set Only One
        if (cheetos.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            KK.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_cheetosActionPerformed

    private void cookieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cookieActionPerformed
        //Set Only One
        if (cookie.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            cheetos.setSelected(false);
            KK.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_cookieActionPerformed

    private void doritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doritosActionPerformed
        //Set Only One
        if (doritos.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            KK.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_doritosActionPerformed

    private void KKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KKActionPerformed
        //Set Only One
        if (KK.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_KKActionPerformed

    private void laysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laysActionPerformed
        //Set Only One
        if (lays.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            KK.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_laysActionPerformed

    private void nutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutsActionPerformed
        //Set Only One
        if (nuts.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            KK.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_nutsActionPerformed

    private void pretzelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pretzelActionPerformed
        //Set Only One
        if (pretzel.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            KK.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_pretzelActionPerformed

    private void rufflesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rufflesActionPerformed
        //Set Only One
        if (ruffles.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            KK.setSelected(false);
            skittles.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_rufflesActionPerformed

    private void skittlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skittlesActionPerformed
        //Set Only One
        if (skittles.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            KK.setSelected(false);
            twix.setSelected(false);
        }
    }//GEN-LAST:event_skittlesActionPerformed

    private void twixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twixActionPerformed
        //Set Only One
        if (twix.isSelected()){
            GB.setSelected(false);
            CLIF.setSelected(false);
            cheetos.setSelected(false);
            cookie.setSelected(false);
            doritos.setSelected(false);
            lays.setSelected(false);
            nuts.setSelected(false);
            pretzel.setSelected(false);
            ruffles.setSelected(false);
            skittles.setSelected(false);
            KK.setSelected(false);
        }
    }//GEN-LAST:event_twixActionPerformed

    private void moneyOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyOPActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_moneyOPActionPerformed

    private void changeOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeOPActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_changeOPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendingMachineUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VendingMachineUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CLIF;
    private javax.swing.JRadioButton GB;
    private javax.swing.JRadioButton KK;
    private javax.swing.JButton buy;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField changeOP;
    private javax.swing.JRadioButton cheetos;
    private javax.swing.JButton clear;
    private javax.swing.JRadioButton cookie;
    private javax.swing.JRadioButton doritos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton lays;
    private javax.swing.JTextField moneyOP;
    private javax.swing.JRadioButton nuts;
    private javax.swing.JRadioButton pretzel;
    private javax.swing.JRadioButton ruffles;
    private javax.swing.JRadioButton skittles;
    private javax.swing.JRadioButton twix;
    // End of variables declaration//GEN-END:variables
}